### ISSUE TITLE
License for use of uclust binary

### ISSUE THREAD

**Issue by rcedgar** [jcmcnch/MGPrimerEval#3]
The README.md file says:

`"You should also email me at mcnichol@alum.mit.edu to get the uclust binary (which cannot be distributed freely on github)."`

Can you please explain why you believe I have authorized distribution of this software by email but not on github?
Thanks,
Robert.

**Comment by jcmcnch** [comment]
This was based on our conversation on the pyNAST github issue. See in particular: https://github.com/biocore/pynast/issues/21#issuecomment-776297342

It would be great if you would be comfortable to include the binary as part of this repo (that would certainly be much more convenient) but I had understood you would prefer to not have it freely downloadable which is why I had suggested email as an alternative. Please let me know to what you would prefer, and I'd be happy either way.

**Comment by rcedgar** [comment]
Oops, ok my bad for forgetting this -- apologies for the implication it was not authorized. This is fine.

**Comment by jcmcnch** [comment]
Thanks a lot Robert, I'll include the binary in the repo going forward. Much obliged! -Jesse
